# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='duration_time',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Dura\xe7\xe3o (min)'),
        ),
    ]
