# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170207_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.CharField(choices=[('Em Breve', 'Em Breve'), ('Em Andamento', 'Em Andamento'), ('Terminado', 'Terminado')], default='Em Breve', max_length=100, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.AlterField(
            model_name='sport',
            name='duration_time',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Dura\xe7\xe3o geral (min)'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Sport'),
        ),
    ]
