# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20170207_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='Come\xe7a em'),
        ),
    ]
