# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_red', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Pontos Time Vermelho')),
                ('score_blue', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Pontos Time Azul')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Ponto',
                'verbose_name_plural': 'Pontos',
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterField(
            model_name='sport',
            name='duration_time',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Dura\xe7\xe3o geral (min)'),
        ),
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
