# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20170207_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='score_blue',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Pontos Time Azul'),
        ),
        migrations.AddField(
            model_name='game',
            name='score_red',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Pontos Time Vermelho'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
